### DISCUSSION TITLE
AKS demo run - Certificates not found/generated

### DISCUSSION THREAD

**Discussion by AstritCepele** [kedacore/keda-docs#1101] [Q&A]
Hi, 

I am trying to run a demo of KEDA 2.10 in AKS for azure-devops pipeline. I followed the instructions and I did a deployment of helm charts.

I have encountered the below issue that all deployments are failing to mount the certificate:

```
  Warning  FailedMount  12m (x5 over 30m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[certificates kube-api-access-5zwhv]: timed out waiting for the condition
  Warning  FailedMount  4m21s (x23 over 34m)  kubelet            MountVolume.SetUp failed for volume "certificates" : secret "kedaorg-certs" not found
```

Config of certificate block:
```
certificates:
  autoGenerated: true
  secretName: kedaorg-certs
  mountPath: /certs
  certManager:
    enabled: false
    # If generateCA is false, the secret with the CA 
    # has to be annotated with 'cert-manager.io/allow-direct-injection: "true"'
    generateCA: true
    caSecretName: "kedaorg-ca"
```

I investigated the helm charts and I don't understand how the secret is deployed in this case. There is a certificate resource, but on the mentioned conditions it is not deployed. 

Helm version:
❯ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}

AKS version: 1.24.9
