### DISCUSSION TITLE
Using secret on triggers metadata attribute

### DISCUSSION THREAD

**Discussion by robertmujica** [kedacore/keda-docs#373] [Ideas]
Wondering if it is possible to use secret's value instead of hardcoded values during triggers definition

so instead of doing this

metadata:
      bootstrapServers: localhost:9092
      consumerGroup: my-group       # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: test-topic
      # Optional
      lagThreshold: "50"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential

we would do something like

- secretRef:
       name: secret-name
metadata:
      bootstrapServers: BOOTSTRAP_SERVER_FROM_SECRET
      consumerGroup: my-group       # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: TOPIC_FROM_SECRET
      # Optional
      lagThreshold: "50"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential

so we don't have to duplicate this value and expose value for security reasons across a repo.

**Comment by tomkerkhove** [comment]
You can do this by using TriggerAuthentication (https://keda.sh/docs/2.1/concepts/authentication/#re-use-credentials-and-delegate-auth-with-triggerauthentication)

**Reply by robertmujica** [reply]
Nice, let me go through documentation, I thought TriggerAuthentication was specifically for TLS auth but it looks like it has other features / usage.

**Reply by robertmujica** [reply]
is this supported on kafka scaler ? i have tried following setting

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: test
spec:
  secretTargetRef:
  - parameter: bootstrapServers
    name: secret-name
    key: KAFKA_SERVER
  - parameter: topic
    name: secret-name
    key: KAFKA_TOPIC
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    name: deploy-name
  pollingInterval: 30
  minReplicaCount: 6   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: kafka
    metadata:
      consumerGroup: a-consumer-group      # Make sure that this consumer group name is the same one as the one that is consuming topics
      lagThreshold: "5"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```
but when i describe scaleobject i can see following status

Message:               Error checking metric name uniqueness
Reason:                ScaledObjectCheckFailed

and in operator log i can see

"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "kafka-scaledobject", "namespace": "personas-purchases-classification", "error": "error getting scaler for trigger #0: error parsing kafka metadata: no bootstrapServers given"}

yes i can see is because i'm not passing bootstrapServers to metadata, however i thought when i set 

```
authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

it will automatically bind TriggerAuthentication parameters i defined with exact name expected by metadata in this case bootstrapServers.

it looks like this scaler does not know how to bind parameters from TriggerAuthentication to metadata properties, am i missing anything ?
