### ISSUE TITLE
Is it possible to combine multiple k8s secrets into single value in TriggerAuthentication

### ISSUE THREAD

**Issue by oleg-ku-32768** [kedacore/keda-docs#1026]
I have following secret:
```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-database-credentials
data:
  username: ...
  password: ...
```

I want to combine values into new one:
`host: amqp://$(username):$(password)@rbtmq.default.svc.cluster.local:5672`

If it's possibe, may I have an example, please?
