### ISSUE TITLE
Include missing parameters in the documentation for GCP Stackdriver Scaler

### ISSUE THREAD

**Issue by mmorejon** [kedacore/keda-docs#1129]
The following parameters are not described in the docs for the `gcp-stackdriver` scaler: 

* alignmentPeriodSeconds
* alignmentAligner
* alignmentReducer

## Expected Behavior

```yaml
triggers:
- type: gcp-stackdriver
  metadata:
    projectId: my-project-id
    filter: 'metric.type="storage.googleapis.com/network/received_bytes_count" AND resource.type="gcs_bucket" AND metric.label.method="WriteObject" AND resource.label.bucket_name="my-gcp-bucket"'
    targetValue: '100'
    credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_JSON
    alignmentPeriodSeconds: '60'
    alignmentAligner: mean
    alignmentReducer: none
```

## Actual Behavior

```yaml
triggers:
- type: gcp-stackdriver
  metadata:
    projectId: my-project-id
    filter: 'metric.type="storage.googleapis.com/network/received_bytes_count" AND resource.type="gcs_bucket" AND metric.label.method="WriteObject" AND resource.label.bucket_name="my-gcp-bucket"'
    targetValue: '100'
    credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_JSON
```

## Specifications

  - **KEDA Version:** *2.10*
  - **Scaler(s):** *gcp-stackdriver*
