### ISSUE TITLE
[v2] Scaled Job configuration parameter support

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kedacore/keda-docs#224]
I noticed that these parameters are not implemented for v2. 

```yaml
  jobTargetRef:
    parallelism: 1 # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1 # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 600 # Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 6 # Specifies the number of retries before marking this job failed. Defaults to 6
```

We need to discuss the parameter of `parallelism` vs  `maxReplicaCount`.  

* `parallelism` looks similar to `maxReplicaCount`.  The name of `replicaCount` might cause confusion. I'm not sure the backward compatibility of the `maxReplicaCount` (it was not working), one idea is migrate from `maxReplicaCount` to `parallelism` is the one. 
* `completions` keep
* `activeDeadlineSeconds` keep
* `backoffLimit` keep

# Related
https://github.com/kedacore/keda-docs/pull/220
