### ISSUE TITLE
Changes Value in secrets to base64 encoded

### ISSUE THREAD

**Issue by Shubham82** [kedacore/keda-docs#382]
In MySQL  scaler [example](https://keda.sh/docs/2.1/scalers/mysql/#example) in documentation, The values for all keys in the data field in secrets should be base64-encoded strings. but in this it show as string.
```
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: my-project
type: Opaque
data:
  mysql_conn_str: user@tcp(mysql:3306)/stats_db    -------> It should be base64 encoded.
```
if this change sounds legitimate i would like to do it.

Thanks.
