### ISSUE TITLE
Blog files: why add date to file name and use an alias to remove it?

### ISSUE THREAD

**Issue by chalin** [kedacore/keda-docs#707]
Consider the `content/blog/2022-03-10-how-zapier-uses-keda.md` file, recently added via #687, with the following front matter:

```toml
title = "How Zapier uses KEDA"
date = 2022-03-10
# ...
aliases = [
"/blog/how-zapier-uses-keda"
]
```

@tomkerkhove - Why not simply name the file `content/blog/how-zapier-uses-keda.md` and avoid having to define an alias?

By having the alias be different from the file name by dropping the date, makes it easier to inadvertently introduce a clash at some point.

Note that not all blog entries have such an alias defined, so it doesn't seem to be a fully enforced convention (also the [blog archetype](https://github.com/kedacore/keda-docs/blob/main/archetypes/blog.md) doesn't have an alias entry).
